name: guinness
version: 0.1.8
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/guinness
description: A port of the Jasmine testing framework.
dependencies:
  collection: ">=0.9.1 <2.0.0"
  unittest: ">= 0.11.0 <0.12.0"
dev_dependencies:
  dartmocks: ">= 0.5.2 <0.6.0"
environment:
  sdk: ">=1.3.0 <2.0.0"